# Generated by Django 3.2.8 on 2022-05-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0003_rename_mailadress_personmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200, null=True)),
                ('album_title', models.CharField(blank=True, max_length=300, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('album_logo', models.ImageField(blank=True, null=True, upload_to='album_logos/')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.personmodel', verbose_name='Yayınlayıcı')),
            ],
        ),
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicName', models.CharField(blank=True, max_length=80, null=True, verbose_name='Muzik İsmi')),
                ('the_music', models.FileField(blank=True, null=True, upload_to='musics/')),
                ('albums', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Music.albummodel', verbose_name='Albüm')),
                ('music_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.personmodel', verbose_name='Müzik Sahibi')),
            ],
        ),
    ]
