# Generated by Django 3.2.8 on 2022-06-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_albummodel_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='album_logo',
            field=models.FileField(blank=True, null=True, upload_to='album_logos/'),
        ),
    ]
