# Generated by Django 4.0.3 on 2022-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandName', models.CharField(blank=True, max_length=90, null=True, verbose_name='Grup İsmi')),
                ('bandLogo', models.ImageField(blank=True, null=True, upload_to='bandLogos/', verbose_name='Grup Logosu')),
            ],
        ),
    ]
