# Generated by Django 3.2.8 on 2022-06-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_rename_mailadress_personmodel_email'),
        ('Band', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Band.bandmodel', verbose_name='Grup')),
                ('bandUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.personmodel', verbose_name='Grup Üyesi')),
            ],
        ),
    ]
