# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Music_proto import Music_pb2 as Music__proto_dot_Music__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MusicModelControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/Music_proto.MusicModelController/List',
                request_serializer=Music__proto_dot_Music__pb2.MusicModelListRequest.SerializeToString,
                response_deserializer=Music__proto_dot_Music__pb2.MusicModel.FromString,
                )
        self.Create = channel.unary_unary(
                '/Music_proto.MusicModelController/Create',
                request_serializer=Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
                response_deserializer=Music__proto_dot_Music__pb2.MusicModel.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/Music_proto.MusicModelController/Retrieve',
                request_serializer=Music__proto_dot_Music__pb2.MusicModelRetrieveRequest.SerializeToString,
                response_deserializer=Music__proto_dot_Music__pb2.MusicModel.FromString,
                )
        self.Update = channel.unary_unary(
                '/Music_proto.MusicModelController/Update',
                request_serializer=Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
                response_deserializer=Music__proto_dot_Music__pb2.MusicModel.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/Music_proto.MusicModelController/Destroy',
                request_serializer=Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class MusicModelControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicModelControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=Music__proto_dot_Music__pb2.MusicModelListRequest.FromString,
                    response_serializer=Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=Music__proto_dot_Music__pb2.MusicModel.FromString,
                    response_serializer=Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=Music__proto_dot_Music__pb2.MusicModelRetrieveRequest.FromString,
                    response_serializer=Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=Music__proto_dot_Music__pb2.MusicModel.FromString,
                    response_serializer=Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=Music__proto_dot_Music__pb2.MusicModel.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Music_proto.MusicModelController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MusicModelController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Music_proto.MusicModelController/List',
            Music__proto_dot_Music__pb2.MusicModelListRequest.SerializeToString,
            Music__proto_dot_Music__pb2.MusicModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Music_proto.MusicModelController/Create',
            Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
            Music__proto_dot_Music__pb2.MusicModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Music_proto.MusicModelController/Retrieve',
            Music__proto_dot_Music__pb2.MusicModelRetrieveRequest.SerializeToString,
            Music__proto_dot_Music__pb2.MusicModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Music_proto.MusicModelController/Update',
            Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
            Music__proto_dot_Music__pb2.MusicModel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Music_proto.MusicModelController/Destroy',
            Music__proto_dot_Music__pb2.MusicModel.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
