# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Music_proto/Music.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17Music_proto/Music.proto\x12\x0bMusic_proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n\nMusicModel\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tmusicName\x18\x03 \x01(\t\"\'\n\x19MusicModelRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x17\n\x15MusicModelListRequest2\xe8\x02\n\x14MusicModelController\x12G\n\x04List\x12\".Music_proto.MusicModelListRequest\x1a\x17.Music_proto.MusicModel\"\x00\x30\x01\x12<\n\x06\x43reate\x12\x17.Music_proto.MusicModel\x1a\x17.Music_proto.MusicModel\"\x00\x12M\n\x08Retrieve\x12&.Music_proto.MusicModelRetrieveRequest\x1a\x17.Music_proto.MusicModel\"\x00\x12<\n\x06Update\x12\x17.Music_proto.MusicModel\x1a\x17.Music_proto.MusicModel\"\x00\x12<\n\x07\x44\x65stroy\x12\x17.Music_proto.MusicModel\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_MUSICMODEL = DESCRIPTOR.message_types_by_name['MusicModel']
_MUSICMODELRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['MusicModelRetrieveRequest']
_MUSICMODELLISTREQUEST = DESCRIPTOR.message_types_by_name['MusicModelListRequest']
MusicModel = _reflection.GeneratedProtocolMessageType('MusicModel', (_message.Message,), {
  'DESCRIPTOR' : _MUSICMODEL,
  '__module__' : 'Music_proto.Music_pb2'
  # @@protoc_insertion_point(class_scope:Music_proto.MusicModel)
  })
_sym_db.RegisterMessage(MusicModel)

MusicModelRetrieveRequest = _reflection.GeneratedProtocolMessageType('MusicModelRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MUSICMODELRETRIEVEREQUEST,
  '__module__' : 'Music_proto.Music_pb2'
  # @@protoc_insertion_point(class_scope:Music_proto.MusicModelRetrieveRequest)
  })
_sym_db.RegisterMessage(MusicModelRetrieveRequest)

MusicModelListRequest = _reflection.GeneratedProtocolMessageType('MusicModelListRequest', (_message.Message,), {
  'DESCRIPTOR' : _MUSICMODELLISTREQUEST,
  '__module__' : 'Music_proto.Music_pb2'
  # @@protoc_insertion_point(class_scope:Music_proto.MusicModelListRequest)
  })
_sym_db.RegisterMessage(MusicModelListRequest)

_MUSICMODELCONTROLLER = DESCRIPTOR.services_by_name['MusicModelController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MUSICMODEL._serialized_start=69
  _MUSICMODEL._serialized_end=112
  _MUSICMODELRETRIEVEREQUEST._serialized_start=114
  _MUSICMODELRETRIEVEREQUEST._serialized_end=153
  _MUSICMODELLISTREQUEST._serialized_start=155
  _MUSICMODELLISTREQUEST._serialized_end=178
  _MUSICMODELCONTROLLER._serialized_start=181
  _MUSICMODELCONTROLLER._serialized_end=541
# @@protoc_insertion_point(module_scope)
