# Generated by Django 4.0.3 on 2022-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=65, null=True)),
                ('lastName', models.CharField(blank=True, max_length=65, null=True)),
                ('username', models.CharField(blank=True, max_length=75, null=True)),
                ('password', models.CharField(blank=True, max_length=75, null=True)),
                ('mailAdress', models.EmailField(blank=True, max_length=85, null=True)),
            ],
        ),
    ]
