# Generated by Django 3.2.8 on 2022-04-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_personmodel_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='mailAdress',
            new_name='email',
        ),
    ]
