# Generated by Django 3.2.8 on 2022-06-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_rename_mailadress_personmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='firstName',
            new_name='firstname',
        ),
    ]
