# Generated by Django 3.2.8 on 2022-06-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0005_commentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
