# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Person_proto/Person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Person_proto/Person.proto\x12\x0cPerson_proto\x1a\x1bgoogle/protobuf/empty.proto\"\x81\x01\n\x0bPersonModel\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\x05\x12\x11\n\tfirstname\x18\x03 \x01(\t\x12\x10\n\x08lastName\x18\x04 \x01(\t\x12\x10\n\x08username\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t\"\x18\n\x16PersonModelListRequest\"(\n\x1aPersonModelRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xfb\x02\n\x15PersonModelController\x12K\n\x04List\x12$.Person_proto.PersonModelListRequest\x1a\x19.Person_proto.PersonModel\"\x00\x30\x01\x12@\n\x06\x43reate\x12\x19.Person_proto.PersonModel\x1a\x19.Person_proto.PersonModel\"\x00\x12Q\n\x08Retrieve\x12(.Person_proto.PersonModelRetrieveRequest\x1a\x19.Person_proto.PersonModel\"\x00\x12@\n\x06Update\x12\x19.Person_proto.PersonModel\x1a\x19.Person_proto.PersonModel\"\x00\x12>\n\x07\x44\x65stroy\x12\x19.Person_proto.PersonModel\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_PERSONMODEL = DESCRIPTOR.message_types_by_name['PersonModel']
_PERSONMODELLISTREQUEST = DESCRIPTOR.message_types_by_name['PersonModelListRequest']
_PERSONMODELRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['PersonModelRetrieveRequest']
PersonModel = _reflection.GeneratedProtocolMessageType('PersonModel', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMODEL,
  '__module__' : 'Person_proto.Person_pb2'
  # @@protoc_insertion_point(class_scope:Person_proto.PersonModel)
  })
_sym_db.RegisterMessage(PersonModel)

PersonModelListRequest = _reflection.GeneratedProtocolMessageType('PersonModelListRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMODELLISTREQUEST,
  '__module__' : 'Person_proto.Person_pb2'
  # @@protoc_insertion_point(class_scope:Person_proto.PersonModelListRequest)
  })
_sym_db.RegisterMessage(PersonModelListRequest)

PersonModelRetrieveRequest = _reflection.GeneratedProtocolMessageType('PersonModelRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMODELRETRIEVEREQUEST,
  '__module__' : 'Person_proto.Person_pb2'
  # @@protoc_insertion_point(class_scope:Person_proto.PersonModelRetrieveRequest)
  })
_sym_db.RegisterMessage(PersonModelRetrieveRequest)

_PERSONMODELCONTROLLER = DESCRIPTOR.services_by_name['PersonModelController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSONMODEL._serialized_start=73
  _PERSONMODEL._serialized_end=202
  _PERSONMODELLISTREQUEST._serialized_start=204
  _PERSONMODELLISTREQUEST._serialized_end=228
  _PERSONMODELRETRIEVEREQUEST._serialized_start=230
  _PERSONMODELRETRIEVEREQUEST._serialized_end=270
  _PERSONMODELCONTROLLER._serialized_start=273
  _PERSONMODELCONTROLLER._serialized_end=652
# @@protoc_insertion_point(module_scope)
