# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Album_proto/Album.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x41lbum_proto/Album.proto\x12\x0bMusic_proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n\nAlbumModel\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\x13\n\x0b\x61lbum_title\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\"\'\n\x19\x41lbumModelRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x17\n\x15\x41lbumModelListRequest2\xe8\x02\n\x14\x41lbumModelController\x12G\n\x04List\x12\".Music_proto.AlbumModelListRequest\x1a\x17.Music_proto.AlbumModel\"\x00\x30\x01\x12<\n\x06\x43reate\x12\x17.Music_proto.AlbumModel\x1a\x17.Music_proto.AlbumModel\"\x00\x12M\n\x08Retrieve\x12&.Music_proto.AlbumModelRetrieveRequest\x1a\x17.Music_proto.AlbumModel\"\x00\x12<\n\x06Update\x12\x17.Music_proto.AlbumModel\x1a\x17.Music_proto.AlbumModel\"\x00\x12<\n\x07\x44\x65stroy\x12\x17.Music_proto.AlbumModel\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_ALBUMMODEL = DESCRIPTOR.message_types_by_name['AlbumModel']
_ALBUMMODELRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['AlbumModelRetrieveRequest']
_ALBUMMODELLISTREQUEST = DESCRIPTOR.message_types_by_name['AlbumModelListRequest']
AlbumModel = _reflection.GeneratedProtocolMessageType('AlbumModel', (_message.Message,), {
  'DESCRIPTOR' : _ALBUMMODEL,
  '__module__' : 'Album_proto.Album_pb2'
  # @@protoc_insertion_point(class_scope:Music_proto.AlbumModel)
  })
_sym_db.RegisterMessage(AlbumModel)

AlbumModelRetrieveRequest = _reflection.GeneratedProtocolMessageType('AlbumModelRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALBUMMODELRETRIEVEREQUEST,
  '__module__' : 'Album_proto.Album_pb2'
  # @@protoc_insertion_point(class_scope:Music_proto.AlbumModelRetrieveRequest)
  })
_sym_db.RegisterMessage(AlbumModelRetrieveRequest)

AlbumModelListRequest = _reflection.GeneratedProtocolMessageType('AlbumModelListRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALBUMMODELLISTREQUEST,
  '__module__' : 'Album_proto.Album_pb2'
  # @@protoc_insertion_point(class_scope:Music_proto.AlbumModelListRequest)
  })
_sym_db.RegisterMessage(AlbumModelListRequest)

_ALBUMMODELCONTROLLER = DESCRIPTOR.services_by_name['AlbumModelController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALBUMMODEL._serialized_start=69
  _ALBUMMODEL._serialized_end=145
  _ALBUMMODELRETRIEVEREQUEST._serialized_start=147
  _ALBUMMODELRETRIEVEREQUEST._serialized_end=186
  _ALBUMMODELLISTREQUEST._serialized_start=188
  _ALBUMMODELLISTREQUEST._serialized_end=211
  _ALBUMMODELCONTROLLER._serialized_start=214
  _ALBUMMODELCONTROLLER._serialized_end=574
# @@protoc_insertion_point(module_scope)
